### ISSUE TITLE
How to access session variable?

### ISSUE THREAD

**Issue by the-foreigner** [neuland/spring-jade4j#20]
Is there a way to access the session variable in the view?

e.g. `#{session}` ?

**Comment by piupuer** [comment]
+1

**Comment by ctguggbond** [comment]
+1,  and , How to access requestScope variable?

**Comment by the-foreigner** [comment]
You need to set **allowSessionOverride** to **true**. An exception will be thrown if model already contains the same key. If you want to override your model value with the session content when keyes match set **allowSessionOverride** to **true**.

    <bean id="viewResolver" class="de.neuland.jade4j.spring.view.JadeViewResolver">
        <property name="configuration" ref="jadeConfiguration" />
        <property name="renderExceptions" value="true" />
        <property name="exposeSessionAttributes" value="true" />
        <property name="allowSessionOverride" value="true" />
    </bean>
